### PR TITLE
Filter for int first rather than bool

### LINKED ISSUE #49: [5.1] Paginating by 1 using TableGrid
I'm not sure why but paginating by 1 using `TableGrid` causes results to be generated as arrays in column closures? For example:

```php
return $this->table->of('issues', function (TableGrid $table) use ($issue) {
    $table->with($issue)->paginate(1);

    $table->column('title', function (Column $column) {
        $column->value = function(Issue $issue)) {
             // Exception 
        };
    });
});
```

Throws exception:

`Argument 1 passed to App\Http\Presenters\Issue\IssuePresenter::App\Http\Presenters\Issue\{closure}() must be an instance of App\Models\Issue, array given`

However changing `$table->with($issue)->paginate(1);` to `$table->with($issue)->paginate(2);` does not generate this exception and the table is generated normally.

Is there anything I can do to be able to type hint my models in the column value closures like I do when I paginate by more than one? I just need to be able to access my models methods for certain closures.

### PR DESCRIPTION
**Pull request by stevebauman**
- Closes #49

### CODE REVIEW

**Comment by stevebauman** [comment]
Thanks!

**Comment by crynobone** [comment]
It currently available in `master` branch (v3.3.x), I backport it in a min (need to fixed the failing test).

**Comment by crynobone** [comment]
Merged and tagged as `v3.1.14`.

**Comment by stevebauman** [comment]
Perfect thanks a ton!

**Pull request merged**
